### ISSUE TITLE
Airplay Mirror packet headers

### ISSUE THREAD

**Issue by koush** [nto/nto.github.com#3]
Hi, thanks for this awesome documentation on Airplay. I've gotten airplay screen mirroring (actual mirroring, not just the simple video playback) working from an Android device. This requires a custom build of Android.

Anyways, the problem I'm running into is that it the mirroring doesn't seem to frame/crop the live feed properly. The resultant picture is partially off screen and too large. From my experimentation, it seems that the airplay headers contain what seem to be framing info. Tweaking these bytes in the codec data header seem to adjust the scale and translation of the image on the Apple TV:

Sample first 64 bytes of a header:

```
1f 00 00 00 01 00 06 00 1d 9a 9f 59 ef de 00 00
00 00 58 44 00 00 22 44 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 58 44 00 00 22 44
00 00 50 43 00 00 10 42 00 c0 57 44 00 c0 21 44
```

It seems that the last 48 bytes (last 3 rows) are what affect the feed placement on the TV. I've been working on trying to make heads or tails of it, but haven't put together on what these values mean. For example, changing some of the 44s to a 43 result in the feed going black. My current suspicion is that it may be a transformation matrix, but that does not seem entirely correct either.

Any ideas or thoughts on this?

**Comment by cedricfung** [comment]
Hi @koush , I have found your excellent CM AirPlay mirroring demo. I'm working on a similar project, http://shou.be. It seems you have gone much further than me, could you please share some information about the packet header details?

@nto mentioned it's a 128-byte header, and only the first 64 bytes used, but just list the first 16 bytes, the following 48 bytes not mentioned at all.

Thanks in advance.

**Comment by hussnain** [comment]
Hi can u guys share any demo for mirroring it will be great help thanks

**Comment by cedricfung** [comment]
@hussnain Check this video https://www.youtube.com/watch?v=Ksb5Z2LONV8
